# Site wide configuration
plugins:
  - jekyll-redirect-from

redirect_from:
  - http://ginaedwards.com

title: Gina Edwards, Ph.D., N.C.C.
locale: en_US
description: Licensed Professional Counselor
logo: logo.png
url: http://ginaedwardsphd.com

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Site owner
owner:
  name: Gina Edwards
  avatar: logo.png
